#!/usr/bin/env python3
"""
Builds assets/js/photos.js from the files inside photos/YYYY/.

Images and videos are discovered automatically so the gallery can follow the
folder structure without requiring hand-edited JavaScript entries.
"""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
PHOTOS_DIR = ROOT / "photos"
OUTPUT = ROOT / "assets" / "js" / "photos.js"
START_YEAR = 2001
END_YEAR = 2026

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".heic", ".heif", ".avif"}
VIDEO_EXTENSIONS = {".mp4", ".m4v", ".mov", ".webm"}
POSTER_EXTENSIONS = (".jpg", ".jpeg", ".png", ".webp")


def natural_sort_key(value: str) -> list[object]:
    parts = re.split(r"(\d+)", value.lower())
    return [int(part) if part.isdigit() else part for part in parts]


def make_caption(stem: str, year: int) -> str:
    return str(year)


def find_poster(year_dir: Path, stem: str) -> str | None:
    for suffix in POSTER_EXTENSIONS:
        candidate = year_dir / f"{stem}{suffix}"
        if candidate.exists():
            return candidate.relative_to(ROOT).as_posix()
        poster_candidate = year_dir / f"{stem}-poster{suffix}"
        if poster_candidate.exists():
            return poster_candidate.relative_to(ROOT).as_posix()
    return None


def build_manifest() -> dict[int, list[dict[str, str]]]:
    manifest: dict[int, list[dict[str, str]]] = {}
    for year in range(START_YEAR, END_YEAR + 1):
        year_dir = PHOTOS_DIR / str(year)
        items: list[dict[str, str]] = []
        if year_dir.exists():
            files = [
                path
                for path in year_dir.iterdir()
                if path.is_file() and not path.name.startswith(".")
            ]
            for path in sorted(files, key=lambda file_path: natural_sort_key(file_path.name)):
                suffix = path.suffix.lower()
                if suffix not in IMAGE_EXTENSIONS and suffix not in VIDEO_EXTENSIONS:
                    continue

                item = {
                    "src": path.relative_to(ROOT).as_posix(),
                    "caption": make_caption(path.stem, year),
                }
                if suffix in VIDEO_EXTENSIONS:
                    item["type"] = "video"
                    poster = find_poster(year_dir, path.stem)
                    if poster:
                        item["poster"] = poster
                items.append(item)
        manifest[year] = items
    return manifest


def write_manifest(manifest: dict[int, list[dict[str, str]]]) -> None:
    header = (
        "/*\n"
        "  This file is auto-generated by scripts/refresh_gallery_manifest.py.\n"
        "  Add photos or videos under photos/YYYY/ and rerun the script to refresh.\n"
        "*/\n"
        "window.GANESH_PHOTOS = {\n"
    )

    lines = [header]
    for year in range(START_YEAR, END_YEAR + 1):
        payload = json.dumps(manifest[year], ensure_ascii=False)
        lines.append(f"  {year}: {payload},\n")
    lines.append("};\n")
    OUTPUT.write_text("".join(lines), encoding="utf-8")


if __name__ == "__main__":
    write_manifest(build_manifest())
